### ISSUE TITLE
compile c++ to wasm via Emscripten

### ISSUE THREAD

**Issue by movepicker** [lichess-org/stockfish.wasm#32]
Hello

 i want to covert stockfish c++ project to wasm with Emscripten in windows 10

i use this code for compile

`emcc main.cpp`

but this error 

wasm-ld: error: C:\Users\GO\AppData\Local\Temp\emscripten_temp_25b66pq5\main_0.o: undefined symbol: Options
wasm-ld: error: C:\Users\GO\AppData\Local\Temp\emscripten_temp_25b66pq5\main_0.o: undefined symbol: Threads
wasm-ld: error: C:\Users\GO\AppData\Local\Temp\emscripten_temp_25b66pq5\main_0.o: undefined symbol: TT

it is possible to convert c++   to wasm in windows ??? 
also i have visual studio 2019 but only compile .exe not .wasm 
please help ,thank you

**Comment by niklasf** [comment]
You need to compile all the other `.cpp` units as well with the [proper flags](https://github.com/lichess-org/stockfish.wasm/blob/b47be685b5d3cc099e26b0a4d59d1fafe9c252f2/src/Makefile#L243-L252). Here is the command to do so using the `Makefile`: https://github.com/lichess-org/stockfish.wasm/blob/b47be685b5d3cc099e26b0a4d59d1fafe9c252f2/package.json#L23

There are various different methods to install `make` on Windows, but honestly it's probably easiest to just compile on Linux or the subsystem for Linux.

**Comment by movepicker** [comment]
i install linux and install Emscripten 

but when i run this code :

`make ARCH=wasm build -j`

this error 


*************************************************


Config:
debug: 'no'
sanitize: 'no'
optimize: 'yes'
arch: 'any'
bits: '64'
kernel: 'Linux'
os: 'GNU/Linux'
prefetch: 'no'
popcnt: 'yes'
sse: 'no'
pext: 'no'

Flags:
CXX: em++
CXXFLAGS: -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME=Stockfish -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s EXTRA_EXPORTED_RUNTIME_METHODS=[ccall] --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto
LDFLAGS:  -lpthread -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME=Stockfish -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s EXTRA_EXPORTED_RUNTIME_METHODS=[ccall] --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto

Testing config sanity. If this fails, try 'make help' ...

make ARCH=wasm COMP=emscripten all
make[1]: Entering directory '/content/stockfish/src'
em++ -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME="Stockfish" -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto   -c -o benchmark.o benchmark.cpp
em++ -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME="Stockfish" -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto   -c -o bitbase.o bitbase.cpp
em++ -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME="Stockfish" -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto   -c -o bitboard.o bitboard.cpp
em++ -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME="Stockfish" -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto   -c -o endgame.o endgame.cpp
em++ -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME="Stockfish" -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto   -c -o evaluate.o evaluate.cpp
em++ -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME="Stockfish" -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto   -c -o main.o main.cpp
em++ -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME="Stockfish" -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto   -c -o material.o material.cpp
em++ -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME="Stockfish" -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto   -c -o misc.o misc.cpp
em++ -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME="Stockfish" -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto   -c -o movegen.o movegen.cpp
em++ -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME="Stockfish" -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto   -c -o movepick.o movepick.cpp
em++ -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME="Stockfish" -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto   -c -o pawns.o pawns.cpp
em++ -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME="Stockfish" -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto   -c -o position.o position.cpp
em++ -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME="Stockfish" -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto   -c -o psqt.o psqt.cpp
em++ -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME="Stockfish" -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto   -c -o search.o search.cpp
em++ -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME="Stockfish" -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto   -c -o thread.o thread.cpp
em++ -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME="Stockfish" -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto   -c -o timeman.o timeman.cpp
em++ -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME="Stockfish" -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto   -c -o tt.o tt.cpp
em++ -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME="Stockfish" -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto   -c -o uci.o uci.cpp
em++ -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME="Stockfish" -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto   -c -o ucioption.o ucioption.cpp
em++ -Wall -Wcast-qual -fno-exceptions -std=c++11  -s MODULARIZE=1 -s EXPORT_NAME="Stockfish" -s ENVIRONMENT=web,worker,node -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -s EXIT_RUNTIME=0 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" --pre-js pre.js -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=71303168 -s MAXIMUM_MEMORY=2147483648 -s FILESYSTEM=0 --closure 1 -s STRICT=1 -s ASSERTIONS=0 -DNDEBUG -O3 -DIS_64BIT -DNO_PREFETCH -DUSE_POPCNT -flto   -c -o tune.o tune.cpp
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
Traceback (most recent call last):
  File "/usr/share/emscripten/emcc", line 1274, in <module>
    exec('shared.Settings.' + key + ' = ' + value)
  File "<string>", line 1, in <module>
NameErrorWARNING  root:  - (see src/settings.js for valid values)
: name 'Stockfish' is not defined
Traceback (most recent call last):
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
  File "/usr/share/emscripten/emcc", line 1274, in <module>
    WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
exec('shared.Settings.' + key + ' = ' + value)
  File "<string>", line 1, in <module>
NameError: name 'Stockfish' is not defined
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
WARNING  root:  - (see src/settings.js for valid values)
Traceback (most recent call last):
  File "/usr/share/emscripten/emcc", line 1274, in <module>
    Traceback (most recent call last):
  File "/usr/share/emscripten/emcc", line 1274, in <module>
    exec('shared.Settings.' + key + ' = ' + value)
  File "<string>", line 1, in <module>
exec('shared.Settings.' + key + ' = ' + value)
NameError: name 'Stockfish' is not defined
  File "<string>", line 1, in <module>
NameError: name 'Stockfish' is not defined
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
WARNING  root:  - (see src/settings.js for valid values)
Traceback (most recent call last):
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
  File "/usr/share/emscripten/emcc", line 1274, in <module>
    exec('shared.Settings.' + key + ' = ' + value)
  File "<string>", line 1, in <module>
NameError: name 'Stockfish' is not defined
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
WARNING  root:  - (see src/settings.js for valid values)
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
Traceback (most recent call last):
  File "/usr/share/emscripten/emcc", line 1274, in <module>
    exec('shared.Settings.' + key + ' = ' + value)
  File "<string>", line 1, in <module>
NameError: name 'Stockfish' is not defined
Traceback (most recent call last):
  File "/usr/share/emscripten/emcc", line 1274, in <module>
    exec('shared.Settings.' + key + ' = ' + value)
  File "<string>", line 1, in <module>
NameError: name 'Stockfish' is not defined
Traceback (most recent call last):
  File "/usr/share/emscripten/emcc", line 1274, in <module>
    exec('shared.Settings.' + key + ' = ' + value)
  File "<string>", line 1, in <module>
NameError: name 'Stockfish' is not defined
WARNING  root:  - (see src/settings.js for valid values)
Traceback (most recent call last):
WARNING  root:  - (see src/settings.js for valid values)
  File "/usr/share/emscripten/emcc", line 1274, in <module>
    Traceback (most recent call last):
exec('shared.Settings.' + key + ' = ' + value)
  File "<string>", line 1, in <module>
NameError: name 'Stockfish' is not defined
  File "/usr/share/emscripten/emcc", line 1274, in <module>
    exec('shared.Settings.' + key + ' = ' + value)
  File "<string>", line 1, in <module>
NameError: name 'Stockfish' is not defined
<builtin>: recipe for target 'endgame.o' failed
make[1]: *** [endgame.o] Error 1
make[1]: *** Waiting for unfinished jobs....
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
<builtin>: recipe for target 'movepick.o' failed
make[1]: *** [movepick.o] Error 1
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
WARNING  root:  - (see src/settings.js for valid values)
Traceback (most recent call last):
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
Traceback (most recent call last):
  File "/usr/share/emscripten/emcc", line 1274, in <module>
<builtin>: recipe for target 'benchmark.o' failed
make[1]: *** [benchmark.o] Error 1
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
Traceback (most recent call last):
  File "/usr/share/emscripten/emcc", line 1274, in <module>
    exec('shared.Settings.' + key + ' = ' + value)
  File "<string>", line 1, in <module>
NameError: name 'Stockfish' is not defined
WARNING  root:  - (see src/settings.js for valid values)
  File "/usr/share/emscripten/emcc", line 1274, in <module>
    Traceback (most recent call last):
  File "/usr/share/emscripten/emcc", line 1274, in <module>
    exec('shared.Settings.' + key + ' = ' + value)
  File "<string>", line 1, in <module>
NameError: name 'Stockfish' is not defined
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
exec('shared.Settings.' + key + ' = ' + value)
  File "<string>", line 1, in <module>
    exec('shared.Settings.' + key + ' = ' + value)
  File "<string>", line 1, in <module>
NameError: name 'Stockfish' is not defined
NameError: name 'Stockfish' is not defined
Traceback (most recent call last):
<builtin>: recipe for target 'main.o' failed
make[1]: *** [main.o] Error 1
<builtin>: recipe for target 'movegen.o' failed
make[1]: *** [movegen.o] Error 1
  File "/usr/share/emscripten/emcc", line 1274, in <module>
    exec('shared.Settings.' + key + ' = ' + value)
  File "<string>", line 1, in <module>
NameError: name 'Stockfish' is not defined
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
<builtin>: recipe for target 'material.o' failed
make[1]: *** [material.o] Error 1
WARNING  root:  - (see src/settings.js for valid values)
<builtin>: recipe for target 'misc.o' failed
make[1]: *** [misc.o] Error 1
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
Traceback (most recent call last):
<builtin>: recipe for target 'evaluate.o' failed
make[1]: *** [evaluate.o] Error 1
  File "/usr/share/emscripten/emcc", line 1274, in <module>
    WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
exec('shared.Settings.' + key + ' = ' + value)
  File "<string>", line 1, in <module>
NameErrorWARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
: name 'Stockfish' is not defined
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
Traceback (most recent call last):
  File "/usr/share/emscripten/emcc", line 1274, in <module>
    exec('shared.Settings.' + key + ' = ' + value)
  File "<string>", line 1, in <module>
NameError: name 'Stockfish' is not defined
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
Traceback (most recent call last):
  File "/usr/share/emscripten/emcc", line 1274, in <module>
    exec('shared.Settings.' + key + ' = ' + value)
  File "<string>", line 1, in <module>
NameError: name 'Stockfish' is not defined
<builtin>: recipe for target 'timeman.o' failed
make[1]: *** [timeman.o] Error 1
WARNING  root:  - (see src/settings.js for valid values)
Traceback (most recent call last):
  File "/usr/share/emscripten/emcc", line 1274, in <module>
<builtin>: recipe for target 'bitbase.o' failed
make[1]: *** [bitbase.o] Error 1
<builtin>: recipe for target 'ucioption.o' failed
make[1]: *** [ucioption.o] Error 1
    exec('shared.Settings.' + key + ' = ' + value)
  File "<string>", line 1, in <module>
NameError: name 'Stockfish' is not defined
<builtin>: recipe for target 'bitboard.o' failed
make[1]: *** [bitboard.o] Error 1
<builtin>: recipe for target 'uci.o' failed
make[1]: *** [uci.o] Error 1
<builtin>: recipe for target 'pawns.o' failed
make[1]: *** [pawns.o] Error 1
<builtin>: recipe for target 'psqt.o' failed
make[1]: *** [psqt.o] Error 1
<builtin>: recipe for target 'thread.o' failed
make[1]: *** [thread.o] Error 1
<builtin>: recipe for target 'tune.o' failed
make[1]: *** [tune.o] Error 1
<builtin>: recipe for target 'search.o' failed
make[1]: *** [search.o] Error 1
<builtin>: recipe for target 'position.o' failed
make[1]: *** [position.o] Error 1
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
Traceback (most recent call last):
  File "/usr/share/emscripten/emcc", line 1274, in <module>
    exec('shared.Settings.' + key + ' = ' + value)
  File "<string>", line 1, in <module>
NameError: name 'Stockfish' is not defined
<builtin>: recipe for target 'tt.o' failed
make[1]: *** [tt.o] Error 1
make[1]: Leaving directory '/content/stockfish/src'
Makefile:451: recipe for target 'build' failed
make: *** [build] Error 2



****************************************


please help , i cant convert this c++ project to wasm , how can i do this ???

**Comment by movepicker** [comment]
thanks , problem solve  

this is step by step foe beginner  :

`Install make`

`Install Python`

`Install GCC Compiler`

`Install git`

`Install emsdk`

`edit ~/.bashrc` for emsdk source

after all of thing run this main code :

`cd src && make clean && make ARCH=wasm build -j && cd .. && cat preamble.js src/stockfish.js > stockfish.js && cp src/stockfish.worker.js src/stockfish.wasm .`
