### ISSUE TITLE
Multi Threads limitations Problem

### ISSUE THREAD

**Issue by movepicker** [lichess-org/stockfish.wasm#35]
Hello , I See This Program Support Until 32 Threads , My Computer has Only 8 Threads ,  I want To Use 32 Threads For Stockfish Wasm Search 

I Do Not Have 32 Thread But In Main Stockfish Project I Use This Comment And It Work :

`setoption name threads value 32`

How Can I Use This Method In Stockfish Wasm ? Is It Possible ?

**Comment by niklasf** [comment]
Nothing prevents you from sending `setoption name Threads value 32` also to this engine, but note that using more parallelism than your hardware provides will just make analysis slower without any benefit.

**Comment by movepicker** [comment]
no , when increase thread the result **best move** changed 

when number of thread was little the result **best move** is false 

for example :

`setoption name Threads value 8`

`go depth 10`

**bestmove a2a4**

`setoption name Threads value 32`

`go depth 10`

**bestmove d2d4**


it is not important number of computer thread!!

but it is important  `setoption name Threads value`
