### ISSUE TITLE
stockfish.js.mem lost file in version 5

### ISSUE THREAD

**Issue by movepicker** [lichess-org/stockfish.wasm#36]
Hello I download stockfish wasm version 5 from this link:

https://github.com/lichess-org/stockfish.wasm/tree/v0.5.11

and make project :

`make ARCH=wasm build -j`

but when it compile ,  i cant find `stockfish.js.mem` 

only i see this file :

`stockfish.js`
`stockfish.wasm`
`stockfish.worker.js`

how can create `stockfish.js.mem` in version 5 ?

please help , thank you

**Comment by niklasf** [comment]
Hi. The old versions did not have or need that file.
