### ISSUE TITLE
How to handle errors when "set position IMPOSSIBLE_FEN"

### ISSUE THREAD

**Issue by pronode** [lichess-org/stockfish.wasm#40]
Hello,

I've problem - when I make Stockfish calculate some impossible position, I get:

```
 worker.js onmessage() captured an uncaught exception: RuntimeError: memory access out of bounds
pthread sent an error! undefined:undefined: memory access out of bounds
```

... which crashes my whole app.
Is there some way to prevent engine from calculating such positions, or handle those errors some way?

**Comment by benediktwerner** [comment]
You could check the position beforehand using something like https://github.com/niklasf/chessops

**Comment by niklasf** [comment]
Note that this is not a limitation of this port, but also the policy of official Stockfish. So doing something else is out of scope for this project.

In chessops v0.12 a sufficient check would look something like:

```js
const maybeLegalPos = parseFen(fen).chain(setup => Chess.fromSetup(setup));
maybeLegalPos.isOk && isStandardMaterial(pos.value)
```
