### ISSUE TITLE
pthread sent an error

### ISSUE THREAD

**Issue by Hugos68** [lichess-org/stockfish.wasm#42]
Whenever importing the script and then doing Stockfish().then... etc
I get the following error printed in my console: pthread sent an error! undefined:undefined: undefined
Why does this happen?

**Comment by niklasf** [comment]
If you run `wasmThreadsSupported()` in the same script, before instanciating Stockfish, what does it return?

**Comment by Hugos68** [comment]
> If you run `wasmThreadsSupported()` as defined at https://github.com/lichess-org/stockfish.wasm#feature-detection  before instanciating Stockfish, what does it return?

It returns true

**Comment by niklasf** [comment]
Ok. Next, can you please check the network console of the browser, reload, and see which files are successfully/unsuccessfully loaded? A screenshot also helps.

**Comment by Hugos68** [comment]
Will do, could be perhaps move this to discord in a lichess support ticket? Might go a bit faster, ill link it here if a solution is found.

**Comment by Hugos68** [comment]
This was fixed by configuring the headers properly
