### ISSUE TITLE
error when building with em++

### ISSUE THREAD

**Issue by ezrnew** [lichess-org/stockfish.wasm#43]
Hello, i have installed the newest version of em++ (3.1) but im getting the following error when trying to build the stockfish.wasm app: 
### error: legacy setting used in strict mode: USE_PTHREADS
I have tried to replace USE_PTHREADS with PTHREADS (which ive read is the newer version of USE_PTHREADS) in MakeFile  which results in another error:
###  PTHREADS is an internal setting and cannot be set from command line
 Im not very familiar with Emscripten, is it an error related to the em++ version?

**Comment by niklasf** [comment]
Hi. That seems likely. The last official build was created using Emscripten 2.0.13, and this repo is  no longer regularly updated.

**Comment by benediktwerner** [comment]
I'd just use the pre-compiled binaries from npm https://npmjs.com/package/stockfish.wasm
